name: Deployment Exercise 1

on:
  pull_request:
    types: opened
    push:
      branches:
        - newbranch
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04 Practice Project (Start)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint script
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy to production
        run: echo "Deploying to production..."
