name: Issues workflow
on: issues  
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue information
        run: |
          echo "Issue title: ${{ toJson(github.event.issue.title) }}"
          echo "Issue body: ${{ toJson(github.event.issue.body) }}"
          echo "Issue number: ${{ toJson(github.event.issue.number) }}"
          echo "Issue URL: ${{ toJson(github.event.issue.html_url) }}"
          echo "Issue state: ${{ toJson(github.event)}}"

